[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 500000
upload_speed = 1500000
board_build.partitions = no_ota.csv
lib_deps = 
    m5stack/M5StickC@^0.2.0
monitor_port = COM3
upload_port = COM3
